version: "3.7"
services:
    frontend:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: impulseincome/client
        ports:
            - "80:3000"
        volumes:
            - ./client:/usr/src/app
        deploy:
            restart_policy:
              condition: on-failure
    backend:
        container_name: server
        build:
            context: ./
            dockerfile: Dockerfile
        image: impulseincome/server
        ports:
            - "5000:5000"
        volumes:
            - ./server:/usr/src/app
        deploy:
            restart_policy:
              condition: on-failure